### ISSUE TITLE
 No module named 'one_extractor' when executing onenote-extract.exe 

### ISSUE THREAD

**Issue by PrahladPawar1733** [volexity/one-extract#1]
onenote-extract.exe __main__.py has a import of  one_extractor.cli but one_extractor folder is not present in site-package instid one_extract is there. 
we have to rename the one_extract folder to one_extractor for the code to execute.

**Comment by alexkornitzer** [comment]
Hi @PrahladPawar1733,

With the release of `hwp-extract` we chose to align the naming and structuring within `one-extract`, as such the folder structure and naming now reflects that of the package name whereas it did not before. This change was applied in `v0.1.0`, so you can pin below that if you are not able to update your Python script to handle this.

Regards,

Alex
